//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisualStudioMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisualStudioMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.VisualStudio.VisualStudioMessages", typeof(VisualStudioMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code factory could not complete the load process. Code factory will not be avaliable at this time. .
        /// </summary>
        public static string CodeFactoryCouldNotLoad {
            get {
                return ResourceManager.GetString("CodeFactoryCouldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal visual studio error occurred, cannot load the document content..
        /// </summary>
        public static string GetDocumentContentUnhandledError {
            get {
                return ResourceManager.GetString("GetDocumentContentUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred locating the parent for project &apos;{0}&apos;. The parent lookup operating cannot complete..
        /// </summary>
        public static string GetParentErrorProjectWithProjectNameReplacement {
            get {
                return ResourceManager.GetString("GetParentErrorProjectWithProjectNameReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while loading the parent of the solution folder &apos;{0}&apos;, cannot complete the load parent operation..
        /// </summary>
        public static string GetParentForSolutionFolderUnhandledErrorWithProjectFolderTitle {
            get {
                return ResourceManager.GetString("GetParentForSolutionFolderUnhandledErrorWithProjectFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while trying to get the parent for the document &apos;{0}&apos;, cannot get the parent model..
        /// </summary>
        public static string GetParentUnhandledErrorForProjectDocumentWithName {
            get {
                return ResourceManager.GetString("GetParentUnhandledErrorForProjectDocumentWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while loading the parent for the project folder &apos;{0}&apos;, the parent model cannot be loaded..
        /// </summary>
        public static string GetParentUnhandledErrorForProjectFolderWithName {
            get {
                return ResourceManager.GetString("GetParentUnhandledErrorForProjectFolderWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while adding content to the document, operation did not complete..
        /// </summary>
        public static string InternalErrorAddDocumentContent {
            get {
                return ResourceManager.GetString("InternalErrorAddDocumentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred the operation could not complete. Review logs for further details..
        /// </summary>
        public static string InternalErrorOccuredCheckLogs {
            get {
                return ResourceManager.GetString("InternalErrorOccuredCheckLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while loading the visual studio document, the operation could not be completed..
        /// </summary>
        public static string LoadDocumentFromSourceUnhandledError {
            get {
                return ResourceManager.GetString("LoadDocumentFromSourceUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing visual studio&apos;s project system, code factory had to cancel the operation. Please try again..
        /// </summary>
        public static string ProjectSystemGeneralError {
            get {
                return ResourceManager.GetString("ProjectSystemGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred will not be able to remove the content from the document..
        /// </summary>
        public static string RemoveContentUnhandledError {
            get {
                return ResourceManager.GetString("RemoveContentUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred will not be able to replace the content in the document..
        /// </summary>
        public static string ReplaceContentUnhandledError {
            get {
                return ResourceManager.GetString("ReplaceContentUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while access the selected item in solution explorer, code factory had to cancel the operation. Please try again..
        /// </summary>
        public static string SolutionExplorerGeneralError {
            get {
                return ResourceManager.GetString("SolutionExplorerGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while loading the child models for the solution folder &apos;{0}&apos;. The load action could not be completed..
        /// </summary>
        public static string SolutionFolderChildLoadUnhandledExceptionWithFolderName {
            get {
                return ResourceManager.GetString("SolutionFolderChildLoadUnhandledExceptionWithFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred while loading the IDocumentContent, operation could not complete..
        /// </summary>
        public static string UnhandledErrorReadingContent {
            get {
                return ResourceManager.GetString("UnhandledErrorReadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code factory has encountered an internal error and cannot load the compiler functionality used by code factory to access .net objects..
        /// </summary>
        public static string VisualStudioCompilerSystemLoadError {
            get {
                return ResourceManager.GetString("VisualStudioCompilerSystemLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code factory has encountered an internal error and cannot load the document writer functionality used by code factory to manage code changes..
        /// </summary>
        public static string VisualStudioDocumentWriterLoadError {
            get {
                return ResourceManager.GetString("VisualStudioDocumentWriterLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code factory has encountered an internal error accessing visual studio. The current operation could not be completed. Please try again..
        /// </summary>
        public static string VisualStudioGeneralError {
            get {
                return ResourceManager.GetString("VisualStudioGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visual studio model could not be loaded. The source model data could not be accessed..
        /// </summary>
        public static string VisualStudioModelLoadError {
            get {
                return ResourceManager.GetString("VisualStudioModelLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code factory has encountered an internal error and cannot load the project system functionality used by code factory to access the project system..
        /// </summary>
        public static string VisualStudioProjectSystemLoadError {
            get {
                return ResourceManager.GetString("VisualStudioProjectSystemLoadError", resourceCulture);
            }
        }
    }
}
