//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFactory.VisualStudio.Loader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFactory.VisualStudio.Configuration.ConfigurationMessages", typeof(ConfigurationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package directory &apos;{0}&apos;. Does not exist exist, cannot load the code factory package configuration. No automation will be loaded..
        /// </summary>
        public static string CannotLocatePackageDirectory {
            get {
                return ResourceManager.GetString("CannotLocatePackageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility that create a CodeFactory configuration and package.\r\nThe following are the command switches supported by the configurtion manager.\r\nThe configuration manager will ignore unknown switches.\r\n\r\nSwitches\r\n? = Displays this help message\r\n\r\nHelp = displays this help message\r\n\r\n/Help = Displays this help message\r\n\r\n/DebugConfig &lt;PathToDLL&gt; = creates a debug configuration for the current project.\r\n.
        /// </summary>
        public static string CommandLineHelpMessage {
            get {
                return ResourceManager.GetString("CommandLineHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Factory Packaging Utility Version {0}\r\nCopyright 2013 LifeCycle Delivery Services, Inc.\r\n.
        /// </summary>
        public static string CommandLineTitle {
            get {
                return ResourceManager.GetString("CommandLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the factory configuration in the package file &apos;{0}&apos;.
        /// </summary>
        public static string ConfigNotInPackage {
            get {
                return ResourceManager.GetString("ConfigNotInPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created the configuration file &apos;{0}&apos;.\r\nConfiguration file has the following resources defined.\r\nAutomation Libraries - &apos;{1}&apos; \r\nSupporting Libraries - &apos;{2}&apos; \r\nAutomation Actions -&apos;{3}&apos; \r\n.
        /// </summary>
        public static string ConfigurationFileCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigurationFileCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code factory .
        /// </summary>
        public static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the factory configuration file, becuase no configuration file was provided..
        /// </summary>
        public static string ConfigurationFileNotProvided {
            get {
                return ResourceManager.GetString("ConfigurationFileNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the configuration file &apos;{0}&apos;.
        /// </summary>
        public static string CreatingConfigurationFile {
            get {
                return ResourceManager.GetString("CreatingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the configuration file &apos;{0}&apos;.
        /// </summary>
        public static string DeletingConfigurationFile {
            get {
                return ResourceManager.GetString("DeletingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the directory that will be used to store the configuration file..
        /// </summary>
        public static string DirectoryDoesNotExistForConfigFile {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExistForConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory configuration could not be loaded from the package file &apos;{0}&apos;.
        /// </summary>
        public static string FactoryConfigCouldNotBeloaded {
            get {
                return ResourceManager.GetString("FactoryConfigCouldNotBeloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the configuration file &apos;{0}&apos;, the following error occured during the creation process, &apos;{1}&apos;.
        /// </summary>
        public static string FailedToCreateConfigurationFile {
            get {
                return ResourceManager.GetString("FailedToCreateConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the configuration file &apos;{0}&apos;, the following error occured during the delete process, &apos;{1}&apos;.
        /// </summary>
        public static string FailedToDeleteConfigFile {
            get {
                return ResourceManager.GetString("FailedToDeleteConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code factory command &apos;{0}&apos;, could not be loaded. This factory command will not avaliable for usage..
        /// </summary>
        public static string FailedToLoadAction {
            get {
                return ResourceManager.GetString("FailedToLoadAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration data, will not be able to create a configuration file..
        /// </summary>
        public static string FailedToLoadConfigurationData {
            get {
                return ResourceManager.GetString("FailedToLoadConfigurationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code factory command &apos;{0}&apos;, could not be loaded due to an invalid assembly path. This factory command will not be loaded..
        /// </summary>
        public static string InvalidAssemblyPath {
            get {
                return ResourceManager.GetString("InvalidAssemblyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured and the Code Factory libraries could not be loaded..
        /// </summary>
        public static string LibrariesNotLoaded {
            get {
                return ResourceManager.GetString("LibrariesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading the library &apos;{0}&apos;, no automation will be loaded..
        /// </summary>
        public static string LibraryLoadError {
            get {
                return ResourceManager.GetString("LibraryLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library &apos;{0}&apos;  was not found in the package. No automation will be loaded..
        /// </summary>
        public static string LibraryNotInPackage {
            get {
                return ResourceManager.GetString("LibraryNotInPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the code factory libraries was not loaded. No automation will be loaded..
        /// </summary>
        public static string LibraryNotLoaded {
            get {
                return ResourceManager.GetString("LibraryNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directory was provided. cannot load libraries..
        /// </summary>
        public static string NoLibraryDirectory {
            get {
                return ResourceManager.GetString("NoLibraryDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package directory was provided cannot load the code factory package configuration. No automation will be loaded..
        /// </summary>
        public static string NoPackageDirectory {
            get {
                return ResourceManager.GetString("NoPackageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No package file was provided, cannot load libraries..
        /// </summary>
        public static string NoPackageFile {
            get {
                return ResourceManager.GetString("NoPackageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code factory did not provide an instance of the commands to be injected into visual studio commands being loaded. No automation will be loaded..
        /// </summary>
        public static string NoVisualStudioActions {
            get {
                return ResourceManager.GetString("NoVisualStudioActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package directory for the package &apos;{0}&apos; could not be created. Cannot load the code factory automation..
        /// </summary>
        public static string PackageDirectoryCannotBeCreated {
            get {
                return ResourceManager.GetString("PackageDirectoryCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target package directory of &apos;{0}&apos;, does not exist. cannot load the package..
        /// </summary>
        public static string PackageDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("PackageDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package file &apos;{0}&apos; could not be found. No automation functionality will be loaded..
        /// </summary>
        public static string PackageFileNotFound {
            get {
                return ResourceManager.GetString("PackageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading the code factory package. No automation will be avaliable with this project..
        /// </summary>
        public static string PackageLoadError {
            get {
                return ResourceManager.GetString("PackageLoadError", resourceCulture);
            }
        }
    }
}
